module.exports.common = [
    ['🐶', "tamer's dog"],
    ['🐒', 'jungle monkey'],
    ['🐱', 'why-would-you-fight-me cat'],
    ['🐈', 'small cat '],
    ['🦌', 'minding-my-own-business deer'],
    ['🐮', 'simple cow'],
    ['🐷', 'backyard pig'],
    ['🐖', 'money bank pig'],
    ['🐗', 'small boar'],
    ['🐑', "Mary's lamb"],
    ['🐐', 'goat'],
    ['🦙', 'llama'],
    ['🦒', 'taller giraffe'],
    ['🐭', 'house rat'],
    ['🐁', 'small mouse'],
    ['🐀', 'pesty rat'],
    ['🐹', 'friendly hamster'],
    ['🐰', 'rabbit'],
    ['🐿️', 'chipmunk'],
    ['🦇', 'bat'],
    ['🐨', 'cool koala'],
    ['🐔', 'chicken'],
    ['🐤', 'no-way-you-are-fighting-me chick'],
    ['🕊️', 'dove'],
    ['🦆', 'yikes duck'],
    ['🦢', 'swan'],
    ['🦉', 'owl'],
    ['🐸', 'swamp frog'],
    ['🦎', 'house lizzard'],
];

module.exports.rare = [
    ['🐵', 'magical satori'],
    ['🐕', 'egyptian hound'],
    ['🦮', 'suspicious chamarosh'],
    ['🐴', 'stray horse'],
    ['🦌', 'angry deer'],
    ['🐂', 'wild oxen'],
    ['🐄', 'giant cow'],
    ['🐗', 'wild boar'],
    ['🐏', 'wild sheep'],
    ['🐐', 'faun'],
    ['🐫', 'double hump camel'],
    ['🐘', 'noraml elephant'],
    ['🦔', 'hedgehog'],
    ['🐼', 'zoo panda'],
    ['🦥', 'sloth'],
    ['🦦', 'harry otter'],
    ['🦨', 'sublime skunk'],
    ['🦘', 'kangaroo'],
    ['🦡', 'badger'],
    ['🐧', 'penguin'],
    ['🕊️', 'peace masters dove'],
    ['🦜', 'tarag parrot'],
    ['🐸', 'goblin'],
    ['🐢', 'apprentice turtle'],
    ['🦎', 'geccko'],
    ['🐍', 'snake'],
];

module.exports.superRare = [
    ['🦧', 'Shojo spirit'],
    ['🐕‍🦺', 'blood-thirsty wild dog'],
    ['🐩', 'snow feline'],
    ['🦝', 'dark tanuki'],
    ['🐯', 'jungle tiger'],
    ['🐆', 'articulan leapord'],
    ['🦌', 'Keresh stag'],
    ['🐃', 'silver buffalo'],
    ['🐏', 'mountain shamshir'],
    ['🐐', 'satyr'],
    ['🐪', 'sun-kissed camel'],
    ['🐘', 'angry elephant'],
    ['🦏', 'rhino'],
    ['🐰', 'alice-in-wonderland rabbit'],
    ['🦇', 'chipacabra'],
    ['🐻', 'bear'],
    ['🦃', 'persian turkey'],
    ['🐓', 'midnight rooster'],
    ['🦅', 'sky eagle'],
    ['🦉', 'strix'],
    ['🐊', 'amazonian crocodile'],
    ['🐍', 'deadly viper'],
];

module.exports.epic = [
    ['🦍', 'ancient primate'],
    ['🐺', 'werewolf fenerir'],
    ['🦁', 'vermillion lion'],
    ['🐅', 'slumber tiger'],
    ['🐘', 'behemoth mammoth'],
    ['🦛', 'crimson hippo'],
    ['🐇', 're-zero rabbit'],
    ['🐼', 'shaolin panda'],
    ['🐦', 'elven harbringer'],
    ['🐧', 'empoleon'],
    ['🦅', 'hippogriff'],
    ['🦩', 'blood pink flame-ingo'],
    ['🦚', 'abysall peacock'],
    ['🐍', 'anaconda'],
    ['🐲', 'valley point drake'],
    ['🦕', 'sauropod'],
];

module.exports.legendary = [
    ['🦊', 'Nine-tailed fox'],
    ['🦄', 'celestial unicorn'],
    ['🦓', 'Mythical Arion'],
    ['🦇', 'camazotz bat god'],
    ['🦅', "empire's griffon"],
    ['🐊', 'aztec cipactli'],
    ['🐢', 'wisdom-god turtlox'],
    ['🐉', 'chineese dragon'],
    ['🦖', 't-rex'],
];
